/**
 * ASTRO_CONSTANTS
 * Global shared data dictionary for all Vedic Astrology prediction modules.
 */

(function() {
    // ========== 1. CORE PLANETS & SIGNS ==========

    const PLANETS = ['Sun', 'Moon', 'Mars', 'Mercury', 'Jupiter', 'Venus', 'Saturn', 'Rahu', 'Ketu'];
    
    const BENEFICS = ['Jupiter', 'Venus', 'Mercury', 'Moon'];
    const MALEFICS = ['Saturn', 'Mars', 'Rahu', 'Ketu'];
    const NEUTRALS = ['Sun'];

    const SIGNS = [
        "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", 
        "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"
    ];

    const SIGN_SYMBOLS = ["♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐", "♑", "♒", "♓"];

    // Mapping of Sign Index (0-11) to its Ruling Planet
    const SIGN_LORDS = {
        0: 'Mars', 1: 'Venus', 2: 'Mercury', 3: 'Moon', 4: 'Sun',
        5: 'Mercury', 6: 'Venus', 7: 'Mars', 8: 'Jupiter', 9: 'Saturn',
        10: 'Saturn', 11: 'Jupiter'
    };

    // ========== 2. DIGNITIES & STRENGTHS ==========

    const EXALTATION_DEGREES = {
        'Sun': 10, 'Moon': 3, 'Mars': 28, 'Mercury': 15, 'Jupiter': 5, 'Venus': 27, 'Saturn': 20
    };

    const DIGNITIES = {
        'Sun':     { exalt: 0,  debilitation: 6,  own: [4] },
        'Moon':    { exalt: 1,  debilitation: 7,  own: [3] },
        'Mars':    { exalt: 9,  debilitation: 3,  own: [0, 7] },
        'Mercury': { exalt: 5,  debilitation: 11, own: [2, 5] },
        'Jupiter': { exalt: 3,  debilitation: 9,  own: [8, 11] },
        'Venus':   { exalt: 11, debilitation: 5,  own: [1, 6] },
        'Saturn':  { exalt: 6,  debilitation: 0,  own: [9, 10] },
        'Rahu':    { exalt: 2,  debilitation: 8,  own: [10] },
        'Ketu':    { exalt: 8,  debilitation: 2,  own: [7] }
    };

    const MULATRIKONA = {
        'Sun':     { sign: 4,  start: 0,  end: 20 },
        'Moon':    { sign: 3,  start: 0,  end: 20 },
        'Mars':    { sign: 0,  start: 0,  end: 12 },
        'Mercury': { sign: 5,  start: 16, end: 20 },
        'Jupiter': { sign: 8,  start: 0,  end: 10 },
        'Venus':   { sign: 6,  start: 0,  end: 15 },
        'Saturn':  { sign: 10, start: 0,  end: 20 }
    };

    const COMBUSTION_ORBS = {
        'Moon': 12, 'Mars': 17, 'Mercury': 14, 'Jupiter': 11, 'Venus': 10, 'Saturn': 15
    };

    const NATURAL_RELATIONSHIPS = {
        'Sun':     { 'Moon': 'Friend', 'Mars': 'Friend', 'Mercury': 'Neutral', 'Jupiter': 'Friend', 'Venus': 'Enemy',  'Saturn': 'Enemy',  'Rahu': 'Enemy',  'Ketu': 'Enemy' },
        'Moon':    { 'Sun': 'Friend',  'Mars': 'Neutral','Mercury': 'Friend',  'Jupiter': 'Neutral','Venus': 'Neutral','Saturn': 'Neutral','Rahu': 'Enemy',  'Ketu': 'Enemy' },
        'Mars':    { 'Sun': 'Friend',  'Moon': 'Friend', 'Mercury': 'Enemy',   'Jupiter': 'Friend', 'Venus': 'Neutral','Saturn': 'Neutral','Rahu': 'Enemy',  'Ketu': 'Friend' },
        'Mercury': { 'Sun': 'Friend',  'Moon': 'Enemy',  'Mars': 'Neutral',    'Jupiter': 'Neutral','Venus': 'Friend', 'Saturn': 'Neutral','Rahu': 'Neutral','Ketu': 'Neutral' },
        'Jupiter': { 'Sun': 'Friend',  'Moon': 'Friend', 'Mars': 'Friend',     'Mercury': 'Enemy',  'Venus': 'Enemy',  'Saturn': 'Neutral','Rahu': 'Neutral','Ketu': 'Neutral' },
        'Venus':   { 'Sun': 'Enemy',   'Moon': 'Enemy',  'Mars': 'Neutral',    'Mercury': 'Friend', 'Jupiter': 'Neutral','Saturn': 'Friend','Rahu': 'Friend', 'Ketu': 'Friend' },
        'Saturn':  { 'Sun': 'Enemy',   'Moon': 'Enemy',  'Mars': 'Enemy',      'Mercury': 'Friend', 'Jupiter': 'Neutral','Venus': 'Friend','Rahu': 'Friend', 'Ketu': 'Enemy' },
        'Rahu':    { 'Sun': 'Enemy',   'Moon': 'Enemy',  'Mars': 'Enemy',      'Mercury': 'Neutral','Jupiter': 'Neutral','Venus': 'Friend','Saturn': 'Friend','Ketu': 'Enemy' },
        'Ketu':    { 'Sun': 'Enemy',   'Moon': 'Enemy',  'Mars': 'Friend',     'Mercury': 'Neutral','Jupiter': 'Neutral','Venus': 'Friend','Saturn': 'Enemy', 'Rahu': 'Enemy' }
    };

    const GEMSTONES = {
        'Sun': 'Ruby', 'Moon': 'Pearl', 'Mars': 'Coral',
        'Mercury': 'Emerald', 'Jupiter': 'Yellow Sapphire',
        'Venus': 'Diamond', 'Saturn': 'Blue Sapphire',
        'Rahu': 'Hessonite (Gomed)', 'Ketu': 'Cat\'s Eye'
    };

    // ========== 3. HOUSE SIGNIFICATIONS ==========

    const HOUSE_NATURE = {
        1:  { type: "Kendra+Trikona", pol: 2,  desc: "Self, body, health" },
        2:  { type: "Maraka/Wealth",  pol: 0,  desc: "Wealth, family, speech" },
        3:  { type: "Upachaya",       pol: 1,  desc: "Courage, siblings, short journeys" },
        4:  { type: "Kendra",         pol: 1,  desc: "Mother, home, vehicles, happiness" },
        5:  { type: "Trikona",        pol: 2,  desc: "Children, talent, love, intelligence" },
        6:  { type: "Dusthana",       pol: -1, desc: "Enemies, disease, debts, service" },
        7:  { type: "Kendra/Maraka",  pol: 1,  desc: "Spouse, marriage, partnerships" },
        8:  { type: "Dusthana",       pol: -2, desc: "Longevity, inheritance, obstacles" },
        9:  { type: "Trikona",        pol: 2,  desc: "Fortune, father, religion, long travel" },
        10: { type: "Kendra+Upachaya",pol: 2,  desc: "Career, honour, profession" },
        11: { type: "Upachaya/Gains", pol: 1,  desc: "Gains, ambitions, elder siblings" },
        12: { type: "Dusthana/Moksha",pol: -1, desc: "Losses, moksha, foreign travel" }
    };

    const HOUSE_SIGNIFICATIONS = {
        1:  { name: "Atma (Self)",       keywords: "Body, health, personality, appearance, longevity", karaka: "Sun" },
        2:  { name: "Dhana (Wealth)",    keywords: "Wealth, family, speech, eyes, food", karaka: "Jupiter, Mercury" },
        3:  { name: "Sahaja (Siblings)", keywords: "Courage, siblings, short journeys, mental strength", karaka: "Mars, Mercury" },
        4:  { name: "Matri (Mother)",    keywords: "Mother, home, vehicles, property, happiness", karaka: "Moon" },
        5:  { name: "Putra (Children)",  keywords: "Children, talent, love, intelligence, romance", karaka: "Jupiter" },
        6:  { name: "Roga (Disease)",    keywords: "Enemies, disease, debts, uncle, service", karaka: "Mars, Saturn" },
        7:  { name: "Kalatra (Spouse)",  keywords: "Marriage, spouse, partnerships, domestic happiness", karaka: "Venus" },
        8:  { name: "Mrityu (Death)",    keywords: "Longevity, dowry, insurance, accidents, inheritance", karaka: "Saturn" },
        9:  { name: "Bhagya (Fortune)",  keywords: "Luck, father, religion, philosophy, distant travel", karaka: "Jupiter, Sun" },
        10: { name: "Karma (Career)",    keywords: "Career, father, honour, trade, respect", karaka: "Sun, Saturn, Mercury" },
        11: { name: "Labha (Gains)",     keywords: "Ambitions, aspirations, fulfillments, elder siblings", karaka: "Jupiter" },
        12: { name: "Vyaya (Loss)",      keywords: "Miseries, sufferings, losses, moksha, foreign travel", karaka: "Ketu, Saturn" }
    };

    // ========== 4. NAKSHATRAS ==========

    const NAKSHATRAS = [
        {
            num: 1,
            name: "Ashwini",
            spanText: "0°00' – 13°20' Aries",
            lord: "Ketu",
            deity: "Ashwini Kumaras (Divine Physicians)",
            symbol: "Horse's Head",
            gana: "Deva",
            nature: "Kshipra (Swift)",
            startDeg: 0,
            endDeg: 13.3333,
            keyTraits: "Swift, healing, pioneering, courageous, energetic",
            strengths: "Healing abilities, leadership, and courage",
            weaknesses: "Impulsiveness and impatience",
            compatibility: "Bharani, Magha, Shatabhisha",
            favorableAspects: "Medicine, surgery, athletics, emergency response, entrepreneurship, swift decision-making, travel",
            unfavorableAspects: "Impatience, leaving projects incomplete, reckless speed",
            professions: "Medicine, surgery, athletics, military service, entrepreneurship",
            interpretation: "Swift action, healing, new beginnings, horse-like energy",
            profile: "Ashwini, the first Nakshatra, carries the energy of new beginnings, speed, and healing. Named after the twin divine physicians of the Vedas, Ashwini natives possess a natural gift for medicine, emergency response, and pioneering action. They are fast starters - sometimes so swift that they leave projects incomplete - but their courage and vitality are unmatched. The horse's head symbol speaks to power directed toward swift movement and service."
        },
        {
            num: 2,
            name: "Bharani",
            spanText: "13°20' – 26°40' Aries",
            lord: "Venus",
            deity: "Yama (God of Death & Dharma)",
            symbol: "Yoni (Womb)",
            gana: "Manushya",
            nature: "Ugra (Fierce)",
            startDeg: 13.3333,
            endDeg: 26.6667,
            keyTraits: "Determined, creative, sensual, responsible, intense",
            strengths: "Endurance, adaptability, and transformative abilities",
            weaknesses: "Stubbornness and possessiveness",
            compatibility: "Ashwini, Purva Phalguni, Rohini, Revati",
            favorableAspects: "Creative pursuits, family-oriented goals, artistic ventures, law, psychology, holding life extremes",
            unfavorableAspects: "Stubbornness, moral extremism, possessiveness",
            professions: "Arts, entertainment, law, psychology, creative industries",
            interpretation: "Transformation, letting go, deep karma, bearer of life",
            profile: "Bharani - 'the bearer' - carries the archetype of transformation, creation, and the courage to hold life's extremes. Ruled by Venus yet presided over by Yama, it bridges beauty and mortality, pleasure and responsibility. Bharani natives are intensely creative, sensually expressive, and deeply determined. They carry their burdens without complaint and often achieve what others consider impossible through sheer force of will."
        },
        {
            num: 3,
            name: "Krittika",
            spanText: "26°40' Aries – 10°00' Taurus",
            lord: "Sun",
            deity: "Agni (God of Fire)",
            symbol: "Razor / Flame",
            gana: "Rakshasa",
            nature: "Mixed",
            startDeg: 26.6667,
            endDeg: 40.0,
            keyTraits: "Sharp, ambitious, purifying, fearless, disciplined",
            strengths: "Clarity, resilience, and analytical skills",
            weaknesses: "Harshness and over-dominance",
            compatibility: "Pushya, Anuradha, Rohini",
            favorableAspects: "Leadership, teaching, strategic roles, military, engineering, surgery, administration",
            unfavorableAspects: "Critical nature, fiery temper, over-demanding expectations",
            professions: "Military, engineering, cooking, surgery, administration, leadership",
            interpretation: "Sharp intelligence, purification, courage, cutting through ignorance",
            profile: "Krittika is the Nakshatra of fire, purification, and sharp discernment. Presided over by Agni and ruled by the Sun, it produces individuals of penetrating intellect, strong ambition, and fierce discipline. The razor symbol speaks to Krittika's power to cut through falsehood and distraction. Krittika natives are natural leaders and commanders."
        },
        {
            num: 4,
            name: "Rohini",
            spanText: "10°00' – 23°20' Taurus",
            lord: "Moon",
            deity: "Brahma (The Creator)",
            symbol: "Ox Cart / Chariot",
            gana: "Manushya",
            nature: "Dhruva (Fixed)",
            startDeg: 40.0,
            endDeg: 53.3333,
            keyTraits: "Creative, sensual, fertile, eloquent, artistic",
            strengths: "Artistic skills, emotional depth, and magnetism",
            weaknesses: "Jealousy and emotional dependency",
            compatibility: "Mrigashira, Hasta, Anuradha",
            favorableAspects: "Agricultural ventures, wealth-building, family affairs, fashion, design, aesthetic industries",
            unfavorableAspects: "Over-attachment, moodiness, indulgence",
            professions: "Arts, business, agriculture, fashion, music, commerce",
            interpretation: "Creativity, fertility, material comforts, growth",
            profile: "Rohini is traditionally considered among the most auspicious of all 27 Nakshatras - and the Moon's favourite where it is exalted. Ruled by the Moon and governed by Brahma the creator, Rohini natives embody beauty, fertility, eloquence, and creative abundance. They possess an innate aesthetic sensibility and a magnetic personal presence."
        },
        {
            num: 5,
            name: "Mrigashira",
            spanText: "23°20' Taurus – 6°40' Gemini",
            lord: "Mars",
            deity: "Soma (Moon God as nectar-bearer)",
            symbol: "Deer's Head",
            gana: "Deva",
            nature: "Mridu (Soft)",
            startDeg: 53.3333,
            endDeg: 66.6667,
            keyTraits: "Curious, gentle, romantic, restless, intelligent",
            strengths: "Intellectual pursuits, adaptability, and charm",
            weaknesses: "Restlessness and indecisiveness",
            compatibility: "Chitra, Revati, Rohini",
            favorableAspects: "Travel, research, creative arts, writing, counselling, communication",
            unfavorableAspects: "Emotional evasiveness, suspicion, lack of commitment",
            professions: "Research, travel, writing, counselling, journalism, creative arts",
            interpretation: "Curiosity, searching, adventure, deer-like grace",
            profile: "Mrigashira - the deer's head - is the Nakshatra of seeking: curious, gentle, and eternally searching. Ruled by Mars yet presided over by the gentle Soma, it produces individuals who are restless seekers of beauty, knowledge, and connection. Mrigashira natives are gifted communicators, researchers, and romantics."
        },
        {
            num: 6,
            name: "Ardra",
            spanText: "6°40' – 20°00' Gemini",
            lord: "Rahu",
            deity: "Rudra (Storm God)",
            symbol: "Teardrop / Diamond",
            gana: "Manushya",
            nature: "Tikshna (Dreadful)",
            startDeg: 66.6667,
            endDeg: 80.0,
            keyTraits: "Transformative, intense, analytical, emotional depth",
            strengths: "Problem-solving, resourcefulness, and resilience",
            weaknesses: "Emotional volatility and rebelliousness",
            compatibility: "Swati, Shatabhisha, Punarvasu, Shravana",
            favorableAspects: "Innovations, scientific pursuits, technology, overcoming adversity, intellectual renewal",
            unfavorableAspects: "Sudden anger, destructive outbursts, deep sorrow",
            professions: "Science, research, technology, philosophy, psychology, investigative fields",
            interpretation: "Destruction, rebuilding, emotional intensity, tears",
            profile: "Ardra, ruled by Rahu and governed by the fierce Rudra, is the Nakshatra of storms, transformation, and breakthrough. The teardrop symbol captures both grief and the diamond of clarity that can emerge from extreme pressure. Ardra natives experience life intensely - sharp emotional fluctuations followed by profound intellectual renewal."
        },
        {
            num: 7,
            name: "Punarvasu",
            spanText: "20°00' Gemini – 3°20' Cancer",
            lord: "Jupiter",
            deity: "Aditi (Mother of the Gods)",
            symbol: "Bow & Quiver",
            gana: "Deva",
            nature: "Chara (Movable)",
            startDeg: 80.0,
            endDeg: 93.3333,
            keyTraits: "Optimistic, wise, generous, versatile, philosophical",
            strengths: "Compassion, adaptability, and renewal abilities",
            weaknesses: "Naivety and inconsistency",
            compatibility: "Pushya, Revati, Vishakha",
            favorableAspects: "Creative pursuits, spiritual growth, teaching, humanitarian work, counselling",
            unfavorableAspects: "Lack of follow-through, over-idealistic expectations",
            professions: "Education, spirituality, writing, counselling, humanitarian work",
            interpretation: "Return, renewal, optimism, restoration",
            profile: "Punarvasu - 'the restorer of goods' - carries the energy of renewal, return, and regeneration. Ruled by Jupiter and presided over by Aditi, the boundless mother, Punarvasu natives are optimistic, generous, philosophically wise, and resilient. They recover naturally from setbacks and inspire those around them."
        },
        {
            num: 8,
            name: "Pushya",
            spanText: "3°20' – 16°40' Cancer",
            lord: "Saturn",
            deity: "Brihaspati (Guru of the Gods)",
            symbol: "Cow's Udder / Lotus",
            gana: "Deva",
            nature: "Kshipra (Swift)",
            startDeg: 93.3333,
            endDeg: 106.6667,
            keyTraits: "Nurturing, devoted, wise, patient, auspicious",
            strengths: "Generosity, devotion, and practicality",
            weaknesses: "Over-cautiousness and emotional suppression",
            compatibility: "Anuradha, Uttara Bhadrapada, Rohini, Punarvasu",
            favorableAspects: "Teaching, parenting, spiritual growth, social work, finance, advisory roles",
            unfavorableAspects: "Rigid dogmatism, slow decision-making, difficulty expressing anger",
            professions: "Teaching, healing, social work, finance, spiritual guidance",
            interpretation: "Nourishment, protection, spiritual growth, prosperity",
            profile: "Pushya is widely regarded as the most auspicious Nakshatra in the entire system. Ruled by Saturn and governed by Brihaspati, Pushya combines nourishment with wisdom. The cow's udder symbolises abundance freely given. Pushya natives are patient, nurturing, deeply devoted, and exceptionally wise advisors."
        },
        {
            num: 9,
            name: "Ashlesha",
            spanText: "16°40' – 30°00' Cancer",
            lord: "Mercury",
            deity: "Nagas (Serpent Deities)",
            symbol: "Coiled Serpent",
            gana: "Rakshasa",
            nature: "Tikshna (Dreadful)",
            startDeg: 106.6667,
            endDeg: 120.0,
            keyTraits: "Mystical, perceptive, cunning, psychic, intense",
            strengths: "Strategic thinking, intelligence, and adaptability",
            weaknesses: "Manipulativeness and emotional detachment",
            compatibility: "Jyeshtha, Swati, Punarvasu, Magha",
            favorableAspects: "Research, counseling, leadership, occult sciences, psychological depth, strategy",
            unfavorableAspects: "Paranoia, deception, possessive attachments",
            professions: "Psychology, occult, research, legal work, medicine, strategy",
            interpretation: "Mystery, wisdom, karmic healing, serpentine energy",
            profile: "Ashlesha - 'the embrace' - is the Nakshatra of the serpent's coil: mystical, perceptive, deeply strategic, and transformative. Ruled by Mercury and governed by the Nagas, Ashlesha produces individuals of penetrating insight, occult knowledge, and natural psychological acuity."
        },
        {
            num: 10,
            name: "Magha",
            spanText: "0°00' – 13°20' Leo",
            lord: "Ketu",
            deity: "Pitrs (Ancestral Spirits)",
            symbol: "Royal Throne",
            gana: "Rakshasa",
            nature: "Ugra (Fierce)",
            startDeg: 120.0,
            endDeg: 133.3333,
            keyTraits: "Regal, traditional, authoritative, proud, generous",
            strengths: "Leadership, respect for tradition, and charisma",
            weaknesses: "Pride, dominance, and resistance to change",
            compatibility: "Ashwini, Bharani, Purva Phalguni, Uttara Phalguni",
            favorableAspects: "Leadership, ancestral guidance, public service, politics, administrative governance",
            unfavorableAspects: "Overbearing attitude, lack of flexibility, royal arrogance",
            professions: "Politics, administration, ancestral business, executive leadership",
            interpretation: "Ancestral power, authority, legacy, throne",
            profile: "Magha - 'the bountiful' - is the Nakshatra of royalty, ancestry, and legacy. Ruled by Ketu and governed by the Pitrs (ancestors), it carries the weight of tradition and the privilege of leadership. Magha natives possess natural authority and a strong sense of heritage."
        },
        {
            num: 11,
            name: "Purva Phalguni",
            spanText: "13°20' – 26°40' Leo",
            lord: "Venus",
            deity: "Bhaga (God of Fortune & Wealth)",
            symbol: "Front Legs of a Bed / Hammock",
            gana: "Manushya",
            nature: "Ugra (Fierce)",
            startDeg: 133.3333,
            endDeg: 146.6667,
            keyTraits: "Creative, romantic, pleasure-loving, charming",
            strengths: "Charm, social skills, and artistic talents",
            weaknesses: "Laziness, indulgence, and over-dependence on others",
            compatibility: "Bharani, Magha, Uttara Phalguni",
            favorableAspects: "Creative arts, partnerships, socializing, entertainment, music, luxury lifestyle",
            unfavorableAspects: "Procrastination, lack of discipline, vanity",
            professions: "Entertainment, arts, music, luxury industries, fashion",
            interpretation: "Creativity, romance, pleasure, front of the bed",
            profile: "Purva Phalguni is the Nakshatra of rest, pleasure, creative expression, and marital happiness. Ruled by Venus and governed by Bhaga, it produces individuals who are naturally charming, artistically gifted, and oriented toward enjoyment, beauty, and partnership."
        },
        {
            num: 12,
            name: "Uttara Phalguni",
            spanText: "26°40' Leo – 10°00' Virgo",
            lord: "Sun",
            deity: "Aryaman (God of Contracts & Patronage)",
            symbol: "Four Legs of a Bed / Cot",
            gana: "Manushya",
            nature: "Dhruva (Fixed)",
            startDeg: 146.6667,
            endDeg: 160.0,
            keyTraits: "Helpful, sociable, reliable, leadership, service",
            strengths: "Loyalty, leadership, and organizational skills",
            weaknesses: "Stubbornness, overburdening oneself, and rigidity",
            compatibility: "Hasta, Revati, Uttara Bhadrapada",
            favorableAspects: "Long-term commitments, community service, social services, business management",
            unfavorableAspects: "Over-attachment, difficulty adapting, self-sacrificing burden",
            professions: "Healthcare, social services, business management, public affairs",
            interpretation: "Service, marriage, fulfillment, back of the bed",
            profile: "Uttara Phalguni brings the social and relational creativity of Purva Phalguni into structure and service. Ruled by the Sun and governed by Aryaman, the deity of noble patronage and contracts, it produces reliable, socially responsible, and service-oriented individuals."
        },
        {
            num: 13,
            name: "Hasta",
            spanText: "10°00' – 23°20' Virgo",
            lord: "Moon",
            deity: "Savitar (Sun God as Vivifier)",
            symbol: "Open Hand / Fist",
            gana: "Deva",
            nature: "Kshipra (Swift)",
            startDeg: 160.0,
            endDeg: 173.3333,
            keyTraits: "Skilled, crafty, intelligent, witty, practical",
            strengths: "Craftsmanship, communication, and wit",
            weaknesses: "Perfectionism, control issues, and emotional instability",
            compatibility: "Chitra, Rohini, Ashwini, Swati",
            favorableAspects: "Practical work, creative arts, negotiations, healing, dexterous craftsmanship",
            unfavorableAspects: "Overthinking, possessiveness, restlessness under stress",
            professions: "Craftsmanship, medicine, commerce, journalism, healing arts",
            interpretation: "Skill, manifestation, craftsmanship, hand",
            profile: "Hasta - 'the hand' - is the Nakshatra of skilled craftsmanship, dexterity, and intelligent application. Ruled by the Moon and governed by Savitar, Hasta natives are witty, practical, skilled with their hands, and commercially astute. The hand symbolises both creation and exchange."
        },
        {
            num: 14,
            name: "Chitra",
            spanText: "23°20' Virgo – 6°40' Libra",
            lord: "Mars",
            deity: "Tvashtar / Vishvakarma (Divine Architect)",
            symbol: "Bright Jewel / Pearl",
            gana: "Rakshasa",
            nature: "Mridu (Soft)",
            startDeg: 173.3333,
            endDeg: 186.6667,
            keyTraits: "Creative, aesthetic, architect-minded, dynamic",
            strengths: "Creativity, confidence, and innovation",
            weaknesses: "Vanity, impulsiveness, and arrogance",
            compatibility: "Swati, Hasta, Mrigashira, Vishakha",
            favorableAspects: "Architecture, design, leadership, visual arts, styling, engineering",
            unfavorableAspects: "Overambition, conflicts with authority, superficial judgment",
            professions: "Architecture, design, art, fashion, engineering, filmmaking",
            interpretation: "Creativity, architecture, brilliance, bright jewel",
            profile: "Chitra - 'the brilliant one' - is the Nakshatra of beauty, architecture, and creative brilliance. Ruled by Mars and governed by Vishvakarma, the divine architect of the cosmos, Chitra natives possess exceptional aesthetic vision, dynamic creative energy, and a drive to build and design."
        },
        {
            num: 15,
            name: "Swati",
            spanText: "6°40' – 20°00' Libra",
            lord: "Rahu",
            deity: "Vayu (Wind God)",
            symbol: "Young Shoot / Coral",
            gana: "Deva",
            nature: "Chara (Movable)",
            startDeg: 186.6667,
            endDeg: 200.0,
            keyTraits: "Independent, adaptable, diplomatic, business-minded",
            strengths: "Flexibility, communication, and resilience",
            weaknesses: "Restlessness, indecision, and over-dependence",
            compatibility: "Ardra, Punarvasu, Hasta, Anuradha",
            favorableAspects: "Trade, public relations, travel, diplomacy, commercial negotiation",
            unfavorableAspects: "Unreliability, emotional detachment, scattered efforts",
            professions: "Business, trade, diplomacy, performing arts, public relations",
            interpretation: "Independence, movement, adaptability, sword",
            profile: "Swati - 'the self-going' - is the Nakshatra of independence, adaptability, and the power of the breeze: gentle yet capable of bending the strongest tree. Ruled by Rahu and governed by Vayu, Swati natives are natural diplomats, business strategists, and performers."
        },
        {
            num: 16,
            name: "Vishakha",
            spanText: "20°00' Libra – 3°20' Scorpio",
            lord: "Jupiter",
            deity: "Indra-Agni (King of Gods & Fire)",
            symbol: "Triumphal Arch / Potter's Wheel",
            gana: "Rakshasa",
            nature: "Mixed",
            startDeg: 200.0,
            endDeg: 213.3333,
            keyTraits: "Goal-oriented, determined, intense, competitive",
            strengths: "Focus, adaptability, and goal-oriented nature",
            weaknesses: "Impatience, over-competitiveness, and stubbornness",
            compatibility: "Anuradha, Mula, Chitra",
            favorableAspects: "Leadership, transformation, teamwork, strategic conquests, political campaigns",
            unfavorableAspects: "Over-aggression, interpersonal conflicts, envy of peers",
            professions: "Politics, law, business, spirituality, executive management",
            interpretation: "Determination, focus, transformation, forked",
            profile: "Vishakha - 'forked branches' - is the Nakshatra of purpose, competitive drive, and eventual triumph. Ruled by Jupiter and governed by the dual deities Indra and Agni, Vishakha natives are goal-oriented, intensely determined, and willing to endure long periods of effort for ultimate success."
        },
        {
            num: 17,
            name: "Anuradha",
            spanText: "3°20' – 16°40' Scorpio",
            lord: "Saturn",
            deity: "Mitra (God of Friendship & Covenants)",
            symbol: "Lotus Flower / Triumphal Arch",
            gana: "Deva",
            nature: "Mridu (Soft)",
            startDeg: 213.3333,
            endDeg: 226.6667,
            keyTraits: "Devoted, organised, compassionate, spiritually inclined",
            strengths: "Perseverance, devotion, and relationship-building",
            weaknesses: "Emotional dependency, possessiveness, and over-seriousness",
            compatibility: "Pushya, Uttara Bhadrapada, Jyeshtha, Vishakha",
            favorableAspects: "Partnership ventures, spiritual growth, counseling, international alliances, group systems",
            unfavorableAspects: "Challenges with emotional openness, brooding resentment",
            professions: "Foreign trade, organisational management, healing, spiritual communities",
            interpretation: "Friendship, devotion, success, following Radha",
            profile: "Anuradha - 'following Radha' - is the Nakshatra of devoted friendship, organisational genius, and spiritual loyalty. Ruled by Saturn and governed by Mitra, Anuradha natives are disciplined, compassionate, and gifted at building lasting communities and systems. The lotus speaks to beauty rising from difficult waters."
        },
        {
            num: 18,
            name: "Jyeshtha",
            spanText: "16°40' – 30°00' Scorpio",
            lord: "Mercury",
            deity: "Indra (King of the Gods)",
            symbol: "Circular Amulet / Umbrella",
            gana: "Rakshasa",
            nature: "Tikshna (Dreadful)",
            startDeg: 226.6667,
            endDeg: 240.0,
            keyTraits: "Protective, ambitious, authoritative, complex, wise",
            strengths: "Leadership, courage, and strategic thinking",
            weaknesses: "Arrogance, self-importance, and emotional rigidity",
            compatibility: "Ashlesha, Revati, Anuradha, Mula",
            favorableAspects: "Authority roles, intellectual pursuits, administration, protective defense, crisis leadership",
            unfavorableAspects: "Overconfidence, tendency to dominate, defensive isolation",
            professions: "Leadership, military, politics, technology, administration",
            interpretation: "Wisdom, seniority, protection, eldest",
            profile: "Jyeshtha - 'the eldest, most excellent' - is the Nakshatra of authority, protectiveness, and wisdom hard-won through experience. Ruled by Mercury and governed by Indra, Jyeshtha natives carry natural leadership, deep ambition, and a strong sense of responsibility for those under their care."
        },
        {
            num: 19,
            name: "Mula",
            spanText: "0°00' – 13°20' Sagittarius",
            lord: "Ketu",
            deity: "Nirriti (Goddess of Dissolution)",
            symbol: "Bundle of Roots / Elephant Goad",
            gana: "Rakshasa",
            nature: "Tikshna (Dreadful)",
            startDeg: 240.0,
            endDeg: 253.3333,
            keyTraits: "Investigative, transformative, philosophical, uprooting",
            strengths: "Deep-rooted knowledge, adaptability, and resilience",
            weaknesses: "Recklessness, destructive tendencies, and emotional intensity",
            compatibility: "Vishakha, Purva Ashadha, Jyeshtha",
            favorableAspects: "Spiritual transformation, research, inquiry, deep diagnostic work, philosophical breakthroughs",
            unfavorableAspects: "Impulsiveness, disruption in relationships, nihilistic extremes",
            professions: "Research, philosophy, medicine, occult sciences, investigative work",
            interpretation: "Roots, destruction, rebirth, root",
            profile: "Mula - 'the root' - is the Nakshatra of radical investigation, uprooting, and philosophical depth. Ruled by Ketu and governed by Nirriti, Mula natives are driven to go to the very root of things - no superficial answer satisfies them. It strips away the inessential to reveal core truth."
        },
        {
            num: 20,
            name: "Purva Ashadha",
            spanText: "13°20' – 26°40' Sagittarius",
            lord: "Venus",
            deity: "Apas (Goddess of Cosmic Waters)",
            symbol: "Elephant Tusk / Fan / Winnowing Basket",
            gana: "Manushya",
            nature: "Ugra (Fierce)",
            startDeg: 253.3333,
            endDeg: 266.6667,
            keyTraits: "Proud, ambitious, creative, persuasive, independent",
            strengths: "Charisma, enthusiasm, and adaptability",
            weaknesses: "Over-indulgence, lack of focus, and procrastination",
            compatibility: "Mula, Uttara Ashadha",
            favorableAspects: "Creative work, emotional expression, social success, legal advocacy, public persuasion",
            unfavorableAspects: "Disorganization, lack of discipline, dogmatic pride",
            professions: "Law, creative industries, teaching, politics, public speaking",
            interpretation: "Invigoration, purification, optimism, earlier victory",
            profile: "Purva Ashadha - 'the early victory' - carries the energy of invincible pride, purification, and the power of persuasion. Ruled by Venus and governed by Apas, it produces individuals who are proud, ambitious, creatively gifted, and highly persuasive. The winnowing basket symbolises discernment."
        },
        {
            num: 21,
            name: "Uttara Ashadha",
            spanText: "26°40' Sagittarius – 10°00' Capricorn",
            lord: "Sun",
            deity: "Vishwadevas (Universal Gods)",
            symbol: "Elephant Tusk / Small Bed",
            gana: "Manushya",
            nature: "Dhruva (Fixed)",
            startDeg: 266.6667,
            endDeg: 280.0,
            keyTraits: "Noble, virtuous, patient, organised, humanitarian",
            strengths: "Perseverance, leadership, and integrity",
            weaknesses: "Rigidity, overburdening oneself, and lack of spontaneity",
            compatibility: "Purva Ashadha, Revati, Shravana",
            favorableAspects: "Leadership roles, justice-oriented work, community service, long-term humanitarian projects",
            unfavorableAspects: "Challenges with adaptability, overwork, excessive austerity",
            professions: "Public service, military honour, humanitarian work, spiritual leadership",
            interpretation: "Victory, perseverance, leadership, later victory",
            profile: "Uttara Ashadha - 'the later victory' - is the Nakshatra of noble, lasting achievement. Ruled by the Sun and governed by the Vishvadevas (universal principles), it produces individuals of exceptional virtue, patience, and humanitarian orientation whose victory endures."
        },
        {
            num: 22,
            name: "Shravana",
            spanText: "10°00' – 23°20' Capricorn",
            lord: "Moon",
            deity: "Vishnu (The Preserver)",
            symbol: "Ear / Three Footprints",
            gana: "Deva",
            nature: "Chara (Movable)",
            startDeg: 280.0,
            endDeg: 293.3333,
            keyTraits: "Wise, perceptive, communicative, devoted, learned",
            strengths: "Listening skills, learning, and emotional intelligence",
            weaknesses: "Over-dependence on tradition, emotional insecurity",
            compatibility: "Dhanishta, Anuradha, Uttara Ashadha",
            favorableAspects: "Teaching, counseling, spiritual guidance, storytelling, knowledge preservation",
            unfavorableAspects: "Emotional rigidity, lack of innovation, hyper-sensitivity to gossip",
            professions: "Counselling, media, teaching, spirituality, storytelling",
            interpretation: "Learning, listening, wisdom, ear",
            profile: "Shravana - 'hearing' - is the Nakshatra of deep listening, learning, and the preservation of wisdom. Ruled by the Moon and governed by Vishnu, Shravana natives are exceptional listeners, teachers, and communicators. The ear symbol speaks to receptive intelligence."
        },
        {
            num: 23,
            name: "Dhanishta",
            spanText: "23°20' Capricorn – 6°40' Aquarius",
            lord: "Mars",
            deity: "Eight Vasus (Celestial Beings of Abundance)",
            symbol: "Drum / Flute",
            gana: "Rakshasa",
            nature: "Chara (Movable)",
            startDeg: 293.3333,
            endDeg: 306.6667,
            keyTraits: "Ambitious, musical, wealthy, generous, courageous",
            strengths: "Hardworking, musical talents, and social skills",
            weaknesses: "Stubbornness, competitiveness, and arrogance",
            compatibility: "Shravana, Purva Bhadrapada, Shatabhisha",
            favorableAspects: "Leadership, creative arts, music, real estate, financial accumulation",
            unfavorableAspects: "Impulsiveness, material excess, domestic friction",
            professions: "Music, real estate, military, management, performing arts",
            interpretation: "Wealth, music, prosperity, drum",
            profile: "Dhanishta - 'the wealthiest' or 'most heard of' - is the Nakshatra of music, rhythm, abundance, and courageous expansion. Ruled by Mars and governed by the eight Vasus, Dhanishta natives are ambitious, musically gifted, generous, and relentlessly industrious."
        },
        {
            num: 24,
            name: "Shatabhisha",
            spanText: "6°40' – 20°00' Aquarius",
            lord: "Rahu",
            deity: "Varuna (God of Cosmic Waters & Hidden Truth)",
            symbol: "Empty Circle / 100 Stars",
            gana: "Rakshasa",
            nature: "Chara (Movable)",
            startDeg: 306.6667,
            endDeg: 320.0,
            keyTraits: "Secretive, healing, scientific, mystical, independent",
            strengths: "Healing abilities, intuition, and problem-solving",
            weaknesses: "Isolation, emotional detachment, and secrecy",
            compatibility: "Ardra, Swati, Dhanishta, Purva Bhadrapada",
            favorableAspects: "Scientific pursuits, innovation, healing, astrology, diagnostic research",
            unfavorableAspects: "Over-isolation, mistrust, feeling misunderstood",
            professions: "Science, research, medicine, astrology, technology, occult healing",
            interpretation: "Healing, mystery, secrets, hundred physicians",
            profile: "Shatabhisha - 'the hundred healers' - is the Nakshatra of secret knowledge, scientific inquiry, and mysterious healing. Ruled by Rahu and governed by Varuna, Shatabhisha natives are independent, secretive, and drawn to the frontiers of knowledge."
        },
        {
            num: 25,
            name: "Purva Bhadrapada",
            spanText: "20°00' Aquarius – 3°20' Pisces",
            lord: "Jupiter",
            deity: "Aja Ekapada (The One-Footed Serpent of Fire)",
            symbol: "Front Legs of a Funeral Bed / Two-Faced Man",
            gana: "Manushya",
            nature: "Ugra (Fierce)",
            startDeg: 320.0,
            endDeg: 333.3333,
            keyTraits: "Intense, idealistic, visionary, eccentric, passionate",
            strengths: "Visionary thinking, determination, and spirituality",
            weaknesses: "Extremism, mood swings, and selfishness",
            compatibility: "Uttara Bhadrapada, Pushya, Shatabhisha",
            favorableAspects: "Spirituality, teaching, philanthropy, deep research, transformational philosophy",
            unfavorableAspects: "Confusion, emotional imbalance, extreme austerity or cynicism",
            professions: "Philosophy, occult, finance, research, spiritual teaching",
            interpretation: "Spiritual warrior, purification, front of the funeral cot",
            profile: "Purva Bhadrapada is the Nakshatra of intense idealism, visionary passion, and the fire of transformation. Ruled by Jupiter and governed by Aja Ekapada, it produces individuals who are passionate about their ideals to the point of eccentricity."
        },
        {
            num: 26,
            name: "Uttara Bhadrapada",
            spanText: "3°20' – 16°40' Pisces",
            lord: "Saturn",
            deity: "Ahir Budhnya (Serpent of the Deep Ocean)",
            symbol: "Back Legs of a Funeral Bed / Twin Snakes",
            gana: "Manushya",
            nature: "Dhruva (Fixed)",
            startDeg: 333.3333,
            endDeg: 346.6667,
            keyTraits: "Wise, compassionate, stable, eloquent, spiritual",
            strengths: "Compassion, perseverance, and stability",
            weaknesses: "Passivity, emotional withdrawal, and lack of ambition",
            compatibility: "Revati, Anuradha, Purva Bhadrapada, Uttara Phalguni",
            favorableAspects: "Long-term goals, spiritual growth, charitable work, meditative wisdom",
            unfavorableAspects: "Over-passivity, reluctance to act, solitude turning to lethargy",
            professions: "Counselling, teaching, legal, charitable work, spiritual guidance",
            interpretation: "Wisdom, compassion, finality, back of the funeral cot",
            profile: "Uttara Bhadrapada is the Nakshatra of deep wisdom, compassionate service, and spiritual eloquence. Ruled by Saturn and governed by Ahir Budhnya, it produces individuals of extraordinary depth, stability, and enduring wisdom."
        },
        {
            num: 27,
            name: "Revati",
            spanText: "16°40' – 30°00' Pisces",
            lord: "Mercury",
            deity: "Pushan (Nourisher & Guide of Souls)",
            symbol: "Fish / Drum",
            gana: "Deva",
            nature: "Mridu (Soft)",
            startDeg: 346.6667,
            endDeg: 360.0,
            keyTraits: "Nurturing, empathetic, artistic, spiritual, idealistic",
            strengths: "Generosity, emotional intelligence, and adaptability",
            weaknesses: "Over-sensitivity, escapism, and lack of focus",
            compatibility: "Punarvasu, Uttara Phalguni, Ashwini, Uttara Bhadrapada",
            favorableAspects: "Arts, spirituality, protection-oriented roles, social welfare, animal care",
            unfavorableAspects: "Emotional overwhelm, disorganization, absorbing others' negativity",
            professions: "Arts, healing, social work, spirituality, travel guidance",
            interpretation: "Completion, nourishment, protection, wealthy",
            profile: "Revati - 'the prosperous' - is the final Nakshatra, completing the zodiac cycle. Ruled by Mercury and governed by Pushan, it carries the cumulative wisdom of all 27 stars. Its natives are deeply nurturing, empathetic, idealistic, and blessed with artistic and spiritual gifts."
        }
        ];

    // ========== 5. SIGN ATTRIBUTES (LAGNA AKSHARA, COLORS & KAAL PURUSH) ==========
    const SIGN_ATTRIBUTES = {
        0: { sign: "Aries", akshara: ["A", "L", "E", "I", "O"], luckyColor: "Red, Coral", kaalPurushHouse: 1, element: "Fire" },
        1: { sign: "Taurus", akshara: ["B", "V", "U", "W"], luckyColor: "White, Cream, Pink", kaalPurushHouse: 2, element: "Earth" },
        2: { sign: "Gemini", akshara: ["K", "Ch", "Gh", "Q", "C"], luckyColor: "Green, Emerald", kaalPurushHouse: 3, element: "Air" },
        3: { sign: "Cancer", akshara: ["D", "H"], luckyColor: "Milky White, Silver", kaalPurushHouse: 4, element: "Water" },
        4: { sign: "Leo", akshara: ["M", "T"], luckyColor: "Gold, Orange, Ruby", kaalPurushHouse: 5, element: "Fire" },
        5: { sign: "Virgo", akshara: ["P", "T", "N", "S"], luckyColor: "Green, Earthy tones", kaalPurushHouse: 6, element: "Earth" },
        6: { sign: "Libra", akshara: ["R", "T"], luckyColor: "White, Light Blue", kaalPurushHouse: 7, element: "Air" },
        7: { sign: "Scorpio", akshara: ["N", "Y"], luckyColor: "Dark Red, Maroon", kaalPurushHouse: 8, element: "Water" },
        8: { sign: "Sagittarius", akshara: ["Bh", "F", "Dh", "Y"], luckyColor: "Yellow, Mustard", kaalPurushHouse: 9, element: "Fire" },
        9: { sign: "Capricorn", akshara: ["Kh", "J"], luckyColor: "Navy Blue, Black", kaalPurushHouse: 10, element: "Earth" },
        10: { sign: "Aquarius", akshara: ["G", "S", "Sh"], luckyColor: "Electric Blue, Grey", kaalPurushHouse: 11, element: "Air" },
        11: { sign: "Pisces", akshara: ["D", "Ch", "Z", "Th"], luckyColor: "Sea Green, Yellow", kaalPurushHouse: 12, element: "Water" }
    };

    // Export to window
    window.ASTRO_CONSTANTS = {
        PLANETS,
        BENEFICS,
        MALEFICS,
        NEUTRALS,
        SIGNS,
        SIGN_SYMBOLS,
        SIGN_LORDS,
        EXALTATION_DEGREES,
        DIGNITIES,
        MULATRIKONA,
        COMBUSTION_ORBS,
        NATURAL_RELATIONSHIPS,
        GEMSTONES,
        HOUSE_NATURE,
        HOUSE_SIGNIFICATIONS,
        NAKSHATRAS,
        SIGN_ATTRIBUTES
    };

})();

// Export for Node/CommonJS compatibility if needed
if (typeof module !== 'undefined' && module.exports) {
    module.exports = window.ASTRO_CONSTANTS;
}